[package]
name = "test-helpers"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = [
    "rt-multi-thread",
    "net",
    "sync",
    "macros",
    "signal",
] }

lazy_static = "1.4"
